package crud;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_siswa extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    
    CRUD aa = new CRUD();

    public Form_siswa() {
        initComponents();
        tampil_database();
    }
    
    // method untuk menampilkan data ke tabel_siswa [JTable]
    public void tampil_database() {
        Object [] baris = {"No Pemesanan","Nama","Jenis Kelamin","Alamat","No Identitas", "Jenis Kamar","Hari","Tarif","Total"}; 
        tabmode = new DefaultTableModel(null, baris); 
        tabel_siswa.setModel(tabmode); try { hasil = 
        aa.tampilData(); while (hasil.next()){ 
        aa.setId(hasil.getString("id")); 
        aa.setNama(hasil.getString("nama")); 
        aa.setAlamat(hasil.getString("alamat"));
        aa.setJenis_kelamin(hasil.getString("jenis_kelamin"));
        aa.setNo_identitas(hasil.getString("no_identitas"));
        aa.setJenis_kamar(hasil.getString("jenis_kamar"));
        aa.setHari(hasil.getString("hari"));
        aa.setTarif(hasil.getString("tarif"));
        aa.setTotal(hasil.getString("total"));
        String[] data = {aa.getId(), aa.getNama(), aa.getAlamat(),
            aa.getJenis_kelamin(),aa.getNo_identitas(),aa.getJenis_kamar(),aa.getHari(),aa.getTarif(),aa.getTotal()}; 
        tabmode.addRow(data);
        }
        } catch (Exception e) {
        }
        }
    
    // method untuk reset text 
    public void reset_text() { 
    txt_id.setText(""); 
    txt_nama.setText(""); 
    txt_alamat.setText("");
    txt_no_identitas.setText("");
    txt_hari.setText("");
    txt_tarif.setText("");
    txt_total.setText("");
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txt_alamat = new javax.swing.JTextField();
        txt_no_identitas = new javax.swing.JTextField();
        txt_hari = new javax.swing.JTextField();
        txt_tarif = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_siswa = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Reservasi ALLO Hotel");
        jLabel1.setPreferredSize(new java.awt.Dimension(222, 100));

        btn_simpan.setMnemonic('S');
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_reset.setMnemonic('R');
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_ubah.setMnemonic('U');
        btn_ubah.setText("Update");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_keluar.setMnemonic('K');
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        id.setText("No Pemesanan ");

        nama.setText("Nama");

        alamat.setText("Jenis Kelamin");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        btn_hapus.setMnemonic('H');
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel2.setText("Alamat ");

        jLabel4.setText("No. Identitas");

        jLabel5.setText("Jenis Kamar");

        jLabel6.setText("Hari");

        jLabel7.setText("Tarif");

        jLabel8.setText("Total");

        jButton7.setText("Hitung");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_no_identitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_identitasActionPerformed(evt);
            }
        });

        txt_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hariActionPerformed(evt);
            }
        });

        txt_tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tarifActionPerformed(evt);
            }
        });

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_siswa);

        jLabel9.setText("/malam");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Prempuan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Delux" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nama)
                                        .addComponent(alamat)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(id))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_no_identitas)
                                            .addComponent(txt_nama)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(255, 255, 255)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_tarif)
                                        .addComponent(txt_hari)
                                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ubah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alamat)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_no_identitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_reset)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus)
                            .addComponent(btn_keluar))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1332, 755);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed
    //klik double tombol btn_simpan untuk menyimpan data
    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    if (txt_id.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, ID belum diisi !"); 
        txt_id.requestFocus();
        } else if (txt_nama.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_nama.requestFocus();
        } else if (jComboBox1.getSelectedItem().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        jComboBox1.requestFocus();
        } else if (txt_alamat.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_alamat.requestFocus();
        }else if (txt_no_identitas.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_no_identitas.requestFocus();
        }else if (jComboBox2.getSelectedItem().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        jComboBox2.requestFocus();
        }else if (txt_hari.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_hari.requestFocus();
        }else if (txt_tarif.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_tarif.requestFocus();
        }else if (txt_total.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_total.requestFocus();
        }else { try { aa.setId(txt_id.getText()); 
        aa.setNama(txt_nama.getText()); 
        aa.setJenis_kelamin(jComboBox1.getSelectedItem().toString());
        aa.setAlamat(txt_alamat.getText()); 
        aa.setNo_identitas(txt_no_identitas.getText()); 
        aa.setJenis_kamar(jComboBox2.getSelectedItem().toString()); 
        aa.setHari(txt_hari.getText()); 
        aa.setTarif(txt_tarif.getText()); 
        aa.setTotal(txt_total.getText()); 
        aa.simpanData(aa.getId(), aa.getNama(), aa.getJenis_kelamin(),aa.getAlamat(), aa.getNo_identitas(), aa.getJenis_kamar(), aa.getHari(), aa.getTarif(), aa.getTotal());
        JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi",
        JOptionPane.INFORMATION_MESSAGE);
        tampil_database();
        reset_text();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal tersimpan" , "Informasi",
        JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed
    // klik double tombol btn_reset untuk reset text
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if (txt_id.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, ID belum diisi !"); 
        txt_id.requestFocus();
        } else if (txt_nama.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Nama belum diisi !"); 
        txt_nama.requestFocus();
        } else if (jComboBox1.getSelectedItem().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        jComboBox1.requestFocus();
        } else if (txt_alamat.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        txt_alamat.requestFocus();
        }else if (txt_no_identitas.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        txt_no_identitas.requestFocus();
        }else if (jComboBox2.getSelectedItem().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        jComboBox2.requestFocus();
        }else if (txt_hari.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        txt_hari.requestFocus();
        }else if (txt_tarif.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        txt_tarif.requestFocus();
        }else if (txt_total.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf, Alamat belum diisi !"); 
        txt_total.requestFocus();
        } else {
        try { 
        aa.setId(txt_id.getText()); 
        aa.setNama(txt_nama.getText()); 
        aa.setAlamat(txt_alamat.getText());
        aa.setJenis_kelamin(jComboBox1.getSelectedItem().toString());
        aa.setNo_identitas(txt_no_identitas.getText());
        aa.setJenis_kamar(jComboBox2.getSelectedItem().toString());
        aa.setHari(txt_hari.getText());
        aa.setTarif(txt_tarif.getText());
        aa.setTotal(txt_total.getText());
        aa.ubahData(aa.getId(), aa.getNama(), aa.getJenis_kelamin(), aa.getAlamat(), aa.getNo_identitas(), aa.getJenis_kamar(), aa.getHari(), aa.getTarif(), aa.getTotal());
        JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
        tampil_database();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal diubah" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btn_ubahActionPerformed
    // klik double tombol btn_hapus untuk menghapus data
    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
     if (txt_id.getText().trim().equals("")){
     JOptionPane.showMessageDialog(null,"Maaf, ID belum diisi !"); 
     txt_id.requestFocus();
     } else { 
     if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?","Warning",2) == JOptionPane.YES_OPTION){
     String id = "";
     try { aa.setId(txt_id.getText()); aa.hapusData(aa.getId());
     JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",
     JOptionPane.INFORMATION_MESSAGE);
     tampil_database(); 
     reset_text();
     } catch (Exception e) {
     JOptionPane.showMessageDialog(null, "Data gagal dihapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
     }
     }
     }
    }//GEN-LAST:event_btn_hapusActionPerformed

   // klik double tombol btn_keluar untuk keluar program
    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Warning",2)== JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void tabel_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_siswaMouseClicked
        try {
            int row = tabel_siswa.rowAtPoint(evt.getPoint());
            String id = tabel_siswa.getValueAt(row, 0).toString();
            String nama = tabel_siswa.getValueAt(row, 1).toString();
            String jenis_kelamin = tabel_siswa.getValueAt(row, 2).toString();
            String alamat = tabel_siswa.getValueAt(row, 3).toString();
            String no_identitas = tabel_siswa.getValueAt(row, 4).toString();
            String jenis_kamar = tabel_siswa.getValueAt(row, 5).toString();
            String hari = tabel_siswa.getValueAt(row, 6).toString();
            String tarif = tabel_siswa.getValueAt(row, 7).toString();
            String total = tabel_siswa.getValueAt(row, 8).toString();
            txt_id.setText(String.valueOf(id));
            txt_nama.setText(String.valueOf(nama));
            jComboBox1.setSelectedItem(String.valueOf(jenis_kelamin));
            txt_alamat.setText(String.valueOf(alamat));
            txt_no_identitas.setText(String.valueOf(no_identitas));
            jComboBox2.setSelectedItem(String.valueOf(jenis_kamar));
            txt_hari.setText(String.valueOf(hari));
            txt_tarif.setText(String.valueOf(tarif));
            txt_total.setText(String.valueOf(total));


        } catch (Exception e) {
        }
    }//GEN-LAST:event_tabel_siswaMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_no_identitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_identitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_identitasActionPerformed

    private void txt_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hariActionPerformed

    private void txt_tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tarifActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int hr, tr, tl;
        hr = Integer.parseInt(txt_hari.getText());
        tr = Integer.parseInt(txt_tarif.getText());
        tl = hr * tr;
        txt_total.setText(String.valueOf(tl));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
//        String jk = jComboBox1.getSelectedItem().toString();
//        if(jComboBox1.getSelectedItem()=="Laki-laki"){
//            
//        }
//        if(jComboBox1.getSelectedItem()=="Prempuan") {
//            
//        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedItem()=="Standard") {
            txt_tarif.setText("500000");
        }
        if(jComboBox2.getSelectedItem()=="Delux") {
            txt_tarif.setText("1000000");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JTable tabel_siswa;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_hari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no_identitas;
    private javax.swing.JTextField txt_tarif;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
